### ISSUE TITLE
unable to use before_symlink_script

### ISSUE THREAD

**Issue by lil-cain** [rackspace-cookbooks/phpstack#283]
I'm trying to set a before_symlink_script in phpstack, and it seems to be ignored. It looks like it's potentially because  https://github.com/rackspace-cookbooks/phpstack/blob/master/recipes/application_php.rb#L98 should be 
`if node.deep_fetch(stackname, node[stackname]['webserver'], sites, port, site_name, 'deployment', 'before_symlink_script_name')`

or even
`if site_opts['deployment']['before_symlink_script_name']`

**Comment by lil-cain** [comment]
Hi,

I'm trying to use this as below

    node.default['phpstack']['nginx']['sites'][port][site]['deployment']['before_symlink_script_name'] = 'env.sh'
    node.default['phpstack']['nginx']['sites'][port][site]['deployment']['before_symlink_script_cookbook'] = customer name
    node.default['phpstack']['nginx']['sites'][port][site]['deployment']['before_symlink_script_template'] = 'some-template.erb'

**Comment by prometheanfire** [comment]
we need deep fetch in case that attribute is not defined
