### ISSUE TITLE
Error executing action `deploy` on resource deploy_revision

### ISSUE THREAD

**Issue by jujugrrr** [rackspace-cookbooks/phpstack#285]
We've just encountered https://github.com/poise/application/issues/53. 
If the `application` cookbook gets fixed we need to upgrade `application` cookbook to the new 4.1.5. However in phpstack we are using the cookbook `application_php` which pins the `application` cookbook to `~> 3.0.0` https://github.com/poise/application_php/blob/master/metadata.rb#L9.

I don't think we need `application_php` for phpstack https://github.com/rackspace-cookbooks/phpstack/blob/master/recipes/application_php.rb#L90-L122

We are waiting for https://github.com/poise/application/issues/53 fix to be released , then if Berks doesn't want to get the new application 4.x we we can try to remove `application_php` from Phpstack.

We need to be careful, as people might use `packages` parameter on application : https://github.com/rackspace-cookbooks/phpstack/blob/master/recipes/application_php.rb#L117

**Comment by prometheanfire** [comment]
what do you mean by 'gets fixed'?  as in pinned?

**Comment by jujugrrr** [comment]
> what do you mean by 'gets fixed'? as in pinned?

I mean if https://github.com/poise/application/issues/53 provides a fix and merge it
