### ISSUE TITLE
docroot should be set to /current in default_unless, not the template

### ISSUE THREAD

**Issue by prometheanfire** [rackspace-cookbooks/phpstack#291]
https://github.com/rackspace-cookbooks/phpstack/blob/master/templates/default/apache2/sites/example.com.erb#L4

**Comment by jujugrrr** [comment]
@prometheanfire Hi. I think we should stick to what we have for now. #303 has close to no value from a cookbook wrapper point of view, as nobody used the default Vhost template. However applying #303 will break all the customer cookbook.

The ratio value/impact doesn't worth it

I think it's time to put Stacks in a "maintenance" mode and to only fix bugs or add critical features. this one is not required according to me.

**Comment by fernandohonig** [comment]
@jujugrrr is this for all stacks? Including platformstack, elkstack, etc?

**Comment by niven01** [comment]
+1 on maintenance mode. Question the value of developing stacks any further.
